[package]
name = "rdf-proofs"
version = "0.2.7"
edition = "2021"
authors = ["yamdan"]
license = "MIT"
repository = "https://github.com/zkp-ld/rdf-proofs"
description = "BBS+ signatures and zero-knowledge proofs for Linked Data"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["parallel"]
rdf-star = ["oxrdf/rdf-star", "oxttl/rdf-star"]
std = ["proof_system/std"]
parallel = ["proof_system/parallel"]
wasmer-js = ["proof_system/wasmer-js"]
wasmer-sys = ["proof_system/wasmer-sys"]

[dependencies]
serde = "1.0"
serde_cbor = "0.11"
serde_with = "3.2"
chrono = "0.4"
oxrdf = { git = "https://github.com/oxigraph/oxigraph.git", rev = "922023b" } # to be fixed once Oxigraph v0.4 is released
oxsdatatypes = { git = "https://github.com/oxigraph/oxigraph.git", rev = "922023b" } # to be fixed once Oxigraph v0.4 is released
oxiri = "0.2"
rdf-canon = { git = "https://github.com/zkp-ld/rdf-canon.git", version = "0.13.0" }
proof_system = { git = "https://github.com/docknetwork/crypto.git", rev = "7a238b9", version = "0.21", default-features = false }
bbs_plus = { git = "https://github.com/docknetwork/crypto.git", rev = "7a238b9", version = "0.15", default-features = false }
ark-ff = { version = "0.4", default-features = false }
ark-ec = { version = "0.4", default-features = false }
ark-std = { version = "0.4", default-features = false }
ark-serialize = { version = "0.4", default-features = false, features = [
    "derive",
] }
ark-bls12-381 = { version = "0.4", default-features = false, features = [
    "curve",
] }
blake2 = { version = "0.10", default-features = false }
multibase = "0.9"

[dev-dependencies]
oxttl = { git = "https://github.com/oxigraph/oxigraph.git", rev = "922023b" } # will be fixed once oxttl is published on crates.io
