[package]
name = "rdf-proofs"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
rdf-star = [ "oxrdf/rdf-star" ]

[dependencies]
chrono = "0.4"
oxrdf = { git = "https://github.com/oxigraph/oxigraph.git", rev = "922023b" }            # to be fixed once Oxigraph v0.4 is released
oxiri = "0.2"
proof_system = "0.21"
rdf-canon = { git = "https://github.com/yamdan/rdf-canon-rust.git", version = "0.11.0" }

[dev-dependencies]
oxttl = { git = "https://github.com/oxigraph/oxigraph.git", rev = "922023b" } # will be fixed once oxttl is published on crates.io
